import os
from dotenv import load_dotenv
from flask import Flask, render_template, request, send_file
from reportlab.pdfgen import canvas
from io import BytesIO

load_dotenv()

from agents.requirement_analyst import analyze
from agents.project_manager import plan
from agents.developer import develop
from agents.tester import test
from agents.documentation import document

app = Flask(__name__)

latest_report = {}


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/analyze", methods=["POST"])
def analyze_project():

    global latest_report

    requirement = request.form["requirement"]

    try:
        requirement_data = analyze(requirement)
        project_data = plan(requirement)
        developer_data = develop(requirement)
        tester_data = test(requirement)
        documentation_data = document(requirement)

    except Exception as e:
        return f"""
        <h2>❌ Error</h2>
        <p>{e}</p>
        """

    latest_report = {
        "requirement": requirement,
        "requirement_data": requirement_data,
        "project_data": project_data,
        "developer_data": developer_data,
        "tester_data": tester_data,
        "documentation_data": documentation_data
    }

    return render_template(
        "result.html",
        requirement=requirement,
        requirement_data=requirement_data,
        project_data=project_data,
        developer_data=developer_data,
        tester_data=tester_data,
        documentation_data=documentation_data
    )


@app.route("/download")
def download():

    global latest_report

    buffer = BytesIO()

    pdf = canvas.Canvas(buffer)

    y = 800

    pdf.setTitle("AI Software Development Report")

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(50, y, "AI Software Development Team Report")

    y -= 40

    pdf.setFont("Helvetica", 12)

    pdf.drawString(
        50,
        y,
        "Project Requirement : " + latest_report.get("requirement", "")
    )

    y -= 30

    pdf.drawString(
        50,
        y,
        "Timeline : " + latest_report["project_data"]["Timeline"]
    )

    y -= 30

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Modules")

    y -= 25
    pdf.setFont("Helvetica", 12)

    for module in latest_report["project_data"]["Modules"]:
        pdf.drawString(70, y, "• " + module)
        y -= 20

    y -= 10

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Frontend")

    y -= 20

    pdf.setFont("Helvetica", 12)
    pdf.drawString(
        70,
        y,
        ", ".join(latest_report["developer_data"]["Frontend"])
    )

    y -= 30

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Backend")

    y -= 20

    pdf.setFont("Helvetica", 12)
    pdf.drawString(
        70,
        y,
        ", ".join(latest_report["developer_data"]["Backend"])
    )

    y -= 30

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Database")

    y -= 20

    pdf.setFont("Helvetica", 12)
    pdf.drawString(
        70,
        y,
        ", ".join(latest_report["developer_data"]["Database"])
    )

    y -= 40

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y, "Generated By")

    y -= 20

    pdf.setFont("Helvetica", 12)
    pdf.drawString(70, y, "AI Software Development Team")

    pdf.save()

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="AI_Project_Report.pdf",
        mimetype="application/pdf"
    )


if __name__ == "__main__":
    app.run(debug=True)